version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
  frontend:
    image: node:22-alpine
    working_dir: /ui
    volumes:
      - ./frontend:/ui
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: legallens
      POSTGRES_PASSWORD: legallens
      POSTGRES_DB: legallens
    ports:
      - "5432:5432"
